server:
  port: 8080
  servlet:
    context-path: /myVote

#mybatis的配置
mybatis:
  #config-location: mybatis-config.xml 如果保留了这个配置文件可以这样配置
  #配置数据库实体对象的位置和mapper映射文件的位置
  type-aliases-package: com.cssl.pojo
  mapper-locations: classpath:com/cssl/mapper/*.xml #也可以用注解扫描接口
  configuration:
    auto-mapping-behavior: full
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

spring:
  #数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myvote?serverTimezone=GMT
    username: root
    password: 123456
  #thymeleaf模板引擎
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/templates/,classpath:/META-NF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/upload/
